version: '3'

services:
  nginx:
    image: nginx
    depends_on:
      - php-fpm
    ports:
      - 8888:80
    working_dir: /var/www/app
    volumes:
      - ./app/:/var/www/app:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
  php-fpm:
    build: ./
    working_dir: /var/www/app
    volumes:
      - ./app/:/var/www/app:ro
      - ./php-fpm/php-fpm.conf:/etc/php-fpm.conf:ro
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
  memcached1:
    build: ./memcached/
    container_name: memcached1_alias
  memcached2:
    build: ./memcached/
    container_name: memcached2_alias
  memcached3:
    build: ./memcached/
    container_name: memcached3_alias
  memcached4:
    build: ./memcached/
    container_name: memcached4_alias
  memcached5:
    build: ./memcached/
    container_name: memcached5_alias
